### ISSUE TITLE
Arreglar relaciones en la DB

### ISSUE THREAD

**Issue by MariaJuarez** [MariaJuarez/somosDummies#8]
Debe quedar la relacion de la siguiente forma:

Empleado apunta:
-CargoRHPRO
-Area
-Usuario
-Tecnologia (agregar campo)
-Senority (crear tabla y agregar campo)

Cliente apunta:
-Empleado
-Rubro

Proyecto apunta:
-Cliente
-TipoProyecto
-Tecnologia

Tecnologia apunta::
-TipoTecnologia
-Senority (usar la misma tabla que se crea para empleado)

**Comment by daniellopera15** [comment]
Empleado, falta decidir que sucederá con la relación proyectosEmpleados.

**Comment by daniellopera15** [comment]
Cliente, falta decir que sucederá con la relación proyecto.

**Comment by daniellopera15** [comment]
Proyecto, falta decidir que sucederá con la relación proyectosEmpleados

**Comment by daniellopera15** [comment]
Proyecto apunta a Metodología OneToOne

**Comment by daniellopera15** [comment]
Falta definir el Senority

**Comment by daniellopera15** [comment]
jaja

**Comment by daniellopera15** [comment]
jaja
